spring:
  application:
    name: springcart
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Password!123
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2 hours
    refreshTokenExpiration: 604800 # 7 days